### PR TITLE
Fix: hide menu options until user has logged in

### PR DESCRIPTION
**Pull request by pieterlukasse**
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/VADC-1221

### New Features
- menu options are hidden until user has logged in. This fixes an issue related to missing "teamproject" info and subsequent (transient) login flow error and need to refresh the page

### CODE REVIEW

**Comment by pieterlukasse** [comment]
replaced by https://github.com/uc-cdis/data-portal/pull/1561

**Comment by pieterlukasse** [comment]
reopening, as there seems to be a use case where this is useful.

**Review by tianj7 — APPROVED** [review]

**Comment by pieterlukasse** [comment]
upstream PR: https://github.com/OHDSI/Atlas/pull/3004

**Comment by pieterlukasse** [comment]
addressed upstream PR feedback here: https://github.com/uc-cdis/Atlas/commit/c13024be40a3469bdecde8706577f389fa0d22f1

**Pull request merged**
